
const SEARCH_ENDPOINT = process.env.SEARCH_ENDPOINT
const EMBEDDING_ENDPOINT = process.env.EMBEDDING_ENDPOINT
const COMPLETION_ENDPOINT = process.env.COMPLETION_ENDPOINT

export {
    SEARCH_ENDPOINT,
    EMBEDDING_ENDPOINT,
    COMPLETION_ENDPOINT
}